builtinsList = [
    decodeURI,
    decodeURIComponent,
    encodeURI,
    encodeURIComponent,
    eval,
    isFinite,
    isNaN,
    Number,
    parseFloat,
    parseInt,
    String,
    alert,
    atob,
    btoa,
    close,
    prompt,
    ((object) -> object.length()),
    ((object) -> object.toLowerCase()),
    ((object) -> object.toUpperCase()),
    ((object) -> object.anchor()),
    ((object) -> object.big()),
    ((object) -> object.blink()),
    ((object) -> object.bold()),
    ((object) -> object.fixed()),
    ((object) -> object.fontcolor()),
    ((object) -> object.fontsize()),
    ((object) -> object.italics()),
    ((object) -> object.link()),
    ((object) -> object.small()),
    ((object) -> object.strike()),
    ((object) -> object.sub()),
    ((object) -> object.sup()),
    Math.abs,
    Math.acos,
    Math.asin,
    Math.atan,
    Math.atan2,
    Math.ceil,
    Math.cos,
    Math.exp,
    Math.floor,
    Math.log,
    Math.max,
    Math.min,
    Math.pow,
    Math.random,
    Math.round,
    Math.sin,
    Math.sqrt,
    Math.tan
]

# The paradigm dictates the format in which the code is compiled.
paradigm = 'functional'

baseValidator = -> true